### PR TITLE
feat: remove cmd/vendor and cmd/glide.*

### PR DESCRIPTION
**Pull request by weixiao-huang**
Since we use go modules in `cmd`, there's no need to use vendor directory and glide.*

### CODE REVIEW

**Comment by yue9944882** [comment]
removing cmd/vendor is valid merely for compiling {`apiregister-gen`,`apiserver-boot`}. as a matter of fact, there's another internal release command tools `apiserver-builder-release` which basically compiles kubernetes embedded code-generators and packs them as a tar archive for releases. these generator codes are not tracked by go mod as they are dangling dependencies. we can probably move the release command to a separate folder together w/ the vendor. the vendor will be trimmed a lot as it moves i suppose.

**Comment by weixiao-huang** [comment]
I think `apiserver-builder-release` is unnecessary and the packaging, publish process should be done by bazel. So I try to fix the packaging bug in https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/453

**Comment by yue9944882** [comment]
can this one proceed as the blocker is merged?

**Comment by weixiao-huang** [comment]
Maybe not. Since there seems no bazel support in ci, while opening https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/459 try to test packaging by bazel, the ci could not be passed.

**Comment by weixiao-huang** [comment]
Now this PR rebase https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/459 for testing ci. If https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/459 has been merged, this may also be merged after that.

**Pull request merged**
