### PR TITLE
implement rest.Scoper, return filesystem errors fixes #549

### LINKED ISSUE #549: filepath does not implement rest.Scoper
`error in registering resource: contacts, "burger" must implement scoper`

The storage backend has to implement rest.Scoper

### PR DESCRIPTION
**Pull request by drewwells**

### CODE REVIEW

**Comment by yue9944882** [comment]
the bot is complaining at the commit message, can you revise?

**Comment by drewwells** [comment]
> the bot is complaining at the commit message, can you revise?

what is it asking me to do? I didn't find a clear error message to correct.

**Comment by drewwells** [comment]
@yue9944882 was the jsonfile removed on purpose? https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/538/files#diff-4264db30cf16db2b2bfe965c1d4855dc8852f7a8983be3caef5244186cae547f

I found the example of a custom storage to be quite useful. burger_rest.go also still refers to it so this will lead to a compilation error.

**Comment by drewwells** [comment]
/remove-label do-not-merge/invalid-commit-message

it's complaining about fixes keyword probably

**Comment by yue9944882** [comment]
> @yue9944882 was the jsonfile removed on purpose? https://github.com/kubernetes-sigs/apiserver-builder-alpha/pull/538/files#diff-4264db30cf16db2b2bfe965c1d4855dc8852f7a8983be3caef5244186cae547f

@drewwells yes this will be moved to [apiserver-runtime](https://github.com/kubernetes-sigs/apiserver-runtime) per https://github.com/kubernetes-sigs/apiserver-builder-alpha/issues/541, the mysql storage has already been moved to https://github.com/kubernetes-sigs/apiserver-runtime/tree/main/pkg/experimental/storage/mysql, will be working on jsonfilepath very soon

**Comment by drewwells** [comment]
Can we add it to apiserver before removing it here. The examples won’t build now

**Pull request merged**
