### PR TITLE
ApiVersion is incorrect for Deployment and StatefulSet resources

### PR DESCRIPTION
**Pull request by VitaliyShevchenko**
Apiversion should be updated for Deployment and StatefulSet resources.

### CODE REVIEW

**Comment by yue9944882** [comment]
thanks, please sign the CLA otherwise LGTM

**Comment by yue9944882** [comment]
@VitaliyShevchenko probably it's your commits' author e-mail address doesn't match the binding e-mail address of your GITHUB account..

**Comment by VitaliyShevchenko** [comment]
@k8s-ci-robot /check-cla

**Comment by VitaliyShevchenko** [comment]
@k8s-ci-robot /check-cla

**Comment by yue9944882** [comment]
i believe the CLA check will pass if you drop the first 2 commits from this pull

**Comment by VitaliyShevchenko** [comment]
I wonder, what if a user uses k8s version, which is less than 1.16. I think my fix will not work. I will test it on k8s with version 1.14 or 1.15.
@yue9944882 , what do you think?

**Comment by VitaliyShevchenko** [comment]
> i believe the CLA check will pass if you drop the first 2 commits from this pull

yeah, dropping them right now

**Pull request closed without merging**
